import styles from "../staticPages.module.css";

function TerminosYCondiciones() {
  return (
    <div className={styles.StaticPages}>
      <h1>Términos y Condiciones</h1>
      <p>
        Los términos y condiciones que se describen a continuación (en adelante los "Términos y Condiciones de Uso" o las “Condiciones de Uso”) tienen por objeto regular el comportamiento de los usuarios en el sitio y las relaciones comerciales surgidas de esos comportamientos.
        Se entiende por "Usuario" a toda persona que visite el sitio, aun ocasionalmente, sin importar si el usuario se ha registrado / identificado mediante alguno de los mecanismos provistos al efecto.
        El Propietario y Operador del Sitio es COMPUTAHORRA S.A., CUIT XXXXXXX, con sede social en Córdoba Capital, (Código Postal 5000X) República Argentina. En función de lo expresado ut supra, se fijan en el presente los términos y condiciones a los efectos de reglar el uso por parte del Usuario del sitio computahorra y sus respectivos derechos y obligaciones.
      </p>
      <h2>Naturaleza del servicio y destino del sitio</h2>
      <p>El sitio está destinado a la compra vía online de productos de tecnología. Pueden utilizar estos servicios las personas mayores de edad con capacidad legal para contratar y que acepten los presentes Términos y Condiciones de Uso. Se presumen que titulares o adherentes a tarjetas de crédito tienen esta capacidad. No podrán utilizar el sitio las personas que no tengan esa capacidad ni los menores de edad. Quien registre como Usuario a una persona jurídica, deberá tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en las Condiciones de Uso.</p>
      <h2>Uso de los servicios</h2>
      <p>
        El Usuario, ya sea registrado o visitante, declara que la información que brindará al remitir el pedido de registración será precisa, veraz, correcta y actual siendo a su vez enteramente responsable frente a Computahorra y/o terceros por los daños y perjuicios que el incumplimiento de dicha obligación pudiere acarrear. Proporcionar información inexacta o falsa constituye una violación grave de estos Términos y Condiciones de Uso. El Usuario acepta que utilizará los Servicios exclusivamente con los fines estipulados en (a) los Términos y Condiciones de Uso y (b) cualquier norma o regulación aplicable ya sea de índole municipal, provincial o nacional. Estos Términos y Condiciones de Uso son aplicables a todas las ventas de productos y/o servicios a ser realizadas por Computahorra.
        La realización de un pedido supone la aceptación expresa del Usuario de los presentes Términos y Condiciones de Uso. Confirmando su pedido en el final del proceso de una operación, el Usuario acuerda aceptar los artículos adquiridos, pagar su precio y las condiciones relativas a la adquisición que allí se estipulen, perfeccionando con Computahorra un contrato de compra-venta de bienes muebles.
      </p>
      <h2>Registro e inicio de sesión del usuario</h2>
      <p>Por medio de la aceptación de los Términos y Condiciones de Uso, el Usuario reconoce y acepta que es el único responsable de mantener la confidencialidad de su contraseña. En consecuencia, el Usuario acepta que será el único responsable ante Computahorra y/o terceros de todas y cada una de las actividades que se efectúen en su cuenta en el Sitio. El Usuario deberá notificar de inmediato a Computahorra cualquier uso no autorizado de su contraseña o cuenta del cual tome conocimiento, a través del Sitio o por otro medio. Esta notificación deberá efectuarse a través del Sitio y, adicionalmente, remitiendo una nota al domicilio de Computahorra, debiendo especificar en ambos casos y con el mayor detalle posible toda la información con la que cuente respecto del uso no autorizado de su contraseña.</p>
      <h2>Datos de usuario</h2>
      <p>Al registrarse como Usuario de este Sitio, deberá suministrar información que, a criterio de Computahorra, resulta necesaria para brindar un mejor servicio. Los datos personales del Usuario se toman a los fines de cumplir con el giro comercial de Computahorra, pudiendo realizar acciones de marketing y publicidad. Para el caso que el Usuario decida proporcionar sus datos se acepta que Computahorra pueda utilizarlos con fines operativos del sistema de comercio electrónico organizado en el Sitio y/o en otros sitios web pertenecientes a Computahorra e incluso para comunicare al Usuario por distintos medios ofertas de bienes y servicios, anuncios de promociones, publicidad, siendo la enumeración meramente ejemplificativa.
        El Sitio tiene una estricta política de privacidad y protección de los datos generados por la actividad en línea de sus usuarios. Computahorra S.A no entregará ningún tipo de datos personales ni de información individualizada sobre ninguno de sus Usuarios a ningún tercero, sea en forma gratuita u onerosa, incluyendo cualquier dato relacionado con la identidad de sus usuarios, sus hábitos, costumbres, ámbitos de pertenencia, hábitos de consumo, etc.
        Mediante la aceptación de los Términos y Condiciones de Uso por parte del Usuario se acepta la Política de Privacidad del Sitio, cuyo contenido se encuentra publicado en el mismo.
        El Usuario, en cuanto titular de los datos personales, tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita con intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido al artículo 14, inciso 3 de la Ley n° 25.326. Computahorra aconseja a sus clientes que mantengan actualizados sus datos, pudiendo dirigirse para ello a Consultas@computahorra.com.ar o mediante el ejercicio del derecho de acceso previsto por el art. 14 de la Ley 25.326. Computahorra no solicita datos de sus clientes de forma telefónica o a través del correo electrónico, con excepción de los supuestos estipulados en el punto “Aceptación de Pedidos”. De existir un contacto, tiene como finalidad la realización de alguna encuesta de satisfacción o comunicar alguna promoción o beneficio especial.
        La Dirección Nacional De Protección De Datos Personales, Órgano de Control de la Ley n° 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales, pudiendo el Usuario conocer más en profundidad sobre este tema en la siguiente dirección: www.jus.gov.ar/dnpdp
      </p>
      <h3>Importante</h3>
      <p>Computahorra es una creación ficticia de <a href="https://www.linkedin.com/in/selien-yorbandi-92a582210/" target="__blank">Selien Yorbandi</a> como proyecto personal en la creación de un E-commerce en React. Toda la información relativa a las condiciones de compra son ficticias, no existe ningún compromiso de venta de ningún artículo ni se garantiza ningún derecho al visitante al respecto de los mencionados, ya que no es una empresa real.</p>
    </div>
  );
}

export default TerminosYCondiciones;